spring:
  application:
    name: troy-ats

  data:
    redis:
      host: localhost
      port: 6379

  profiles:
    active: database

  datasource:
    url: jdbc:postgresql://localhost:5432/troy_ats
    username: ats_admin
    password: TroyAts_&1947
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

  security:
    user:
      name: sakaadmin
      password: admin123

server:
  port: 8080

app:
  jwt:
    secret: "super-longest-secret-key-troyats"
    access-ttl-minutes: 30
    refresh-ttl-days: 2

