spring:
  application:
    name: troy-ats

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379

  profiles:
    active: database


  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

  security:
    user:
      name: sakaadmin
      password: admin123

server:
  port: 8080

aws:
  region: ap-south  -1
  s3:
    bucket-name: troy-ats-uploads-prod
    upload-original-cv-dir: upload/originalcv
    upload-troy-cv-dir: upload/troycv
    upload-photo-dir: upload/employee/photo

logging:
  level:
    root: INFO
    com.troy.ats: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web: INFO

app:
  logging:
    dir: ${LOG_DIR}
  jwt:
    secret: ${JWT_SECRET}
    access-ttl-minutes: 30
    refresh-ttl-days: 2

